name: essai
channels:
   - conda-forge
dependencies:
  - google-auth
  - google-cloud-sdk
  - google-cloud-bigquery
  - python
  - numpy
  - ipywidgets
  - pip
  - pip:    
    - pandas
    - matplotlib
